"""Regenerate the pinned, hash-verified AI runtime locks.

Open-ended requirements (``insightface>=0.7``, ``numpy>=1.26``, …) let two
machines install different package sets from the same Image Triage build. That
is not a hypothetical: at the time of writing ``insightface>=0.7`` resolves to
2.0 while the runtime this project was validated against holds 1.0.1.

This script asks pip to resolve each variant *without installing*, and writes a
lock in pip's requirements-with-hashes format. The installer then runs with
``--require-hashes``, so an install either matches the locked set exactly or
fails loudly.

Locks are per interpreter tag and variant::

    packaging/ai_runtime_locks/py313-windows-amd64-gpu.txt
    packaging/ai_runtime_locks/py313-windows-amd64-cpu-base.txt

Run on the target platform with the interpreter the build ships against::

    python scripts/refresh_ai_runtime_lock.py            # every combination
    python scripts/refresh_ai_runtime_lock.py --variant cpu --no-dino

Requires network access. A maintenance tool, never imported at runtime.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from image_triage.ai_paths import runtime_tag  # noqa: E402
from image_triage.ai_runtime_packages import (  # noqa: E402
    AI_RUNTIME_VARIANTS,
    LOCK_DIRECTORY,
    _ai_runtime_pip_requirements_for_variant,
    _torch_index_url_for_variant,
    lock_path_for,
)


def _resolve(variant: str, include_dino: bool) -> list[dict]:
    """Run pip's resolver in report mode and return the resolved distributions."""
    requirements = _ai_runtime_pip_requirements_for_variant(variant, include_dino=include_dino)
    with tempfile.TemporaryDirectory() as temp_dir:
        report_path = Path(temp_dir) / "report.json"
        command = [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--dry-run",
            "--quiet",
            "--ignore-installed",
            "--only-binary=:all:",
            "--extra-index-url",
            _torch_index_url_for_variant(variant),
            "--report",
            str(report_path),
            *requirements,
        ]
        print(f"  resolving {len(requirements)} requirement(s)...", file=sys.stderr, flush=True)
        process = subprocess.run(command, text=True, capture_output=True)
        if process.returncode != 0:
            raise SystemExit(
                f"pip could not resolve {variant} (dino={include_dino}):\n"
                + (process.stderr or process.stdout)
            )
        payload = json.loads(report_path.read_text(encoding="utf-8"))
    return list(payload.get("install", []))


def _canonical(entry: dict) -> str:
    name = str((entry.get("metadata") or {}).get("name") or "")
    return name.replace("_", "-").strip().lower()


def _render(entries: list[dict], variant: str, include_dino: bool) -> str:
    lines = [
        "# Generated by scripts/refresh_ai_runtime_lock.py -- do not edit by hand.",
        f"# interpreter: {runtime_tag()}",
        f"# variant: {variant}   pytorch: {'yes' if include_dino else 'no'}",
        "#",
        "# Every distribution the managed AI runtime installs, pinned to an exact",
        "# version and wheel hash so two machines cannot resolve differently.",
        "",
    ]
    rows: list[tuple[str, str, str]] = []
    for entry in entries:
        canonical = _canonical(entry)
        if variant == "gpu" and canonical == "onnxruntime":
            # onnxruntime and onnxruntime-gpu install the same package
            # directory; keeping both leaves the provider set decided by
            # whichever wheel was unpacked last. insightface pulls the CPU one
            # in transitively, so drop it from the GPU closure.
            print("  dropping transitive onnxruntime from the GPU lock", file=sys.stderr)
            continue
        if canonical == "opencv-python":
            # The application declares the headless wheel. Some dependencies
            # pull the GUI wheel too, but both distributions own the same cv2
            # package tree and cannot safely coexist in one target directory.
            print("  dropping transitive opencv-python from the lock", file=sys.stderr)
            continue
        metadata = entry.get("metadata") or {}
        name = str(metadata.get("name") or "").strip()
        version = str(metadata.get("version") or "").strip()
        archive = (entry.get("download_info") or {}).get("archive_info") or {}
        hashes = archive.get("hashes") or {}
        digest = str(hashes.get("sha256") or "")
        if not digest:
            legacy = str(archive.get("hash") or "")
            if legacy.startswith("sha256="):
                digest = legacy.partition("=")[2]
        if not (name and version and digest):
            raise SystemExit(f"pip reported no usable hash for {name or '<unknown>'} {version}")
        rows.append((name, version, digest))

    for name, version, digest in sorted(rows, key=lambda row: row[0].lower()):
        lines.append(f"{name}=={version} \\")
        lines.append(f"    --hash=sha256:{digest}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--variant", choices=AI_RUNTIME_VARIANTS, action="append")
    parser.add_argument(
        "--no-dino",
        action="store_true",
        help="Only regenerate the compact base locks.",
    )
    parser.add_argument(
        "--dino-only",
        action="store_true",
        help="Only regenerate the full PyTorch locks.",
    )
    args = parser.parse_args(argv)

    variants = tuple(args.variant) if args.variant else AI_RUNTIME_VARIANTS
    if args.no_dino and args.dino_only:
        parser.error("--no-dino and --dino-only are mutually exclusive")
    if args.no_dino:
        dino_choices = (False,)
    elif args.dino_only:
        dino_choices = (True,)
    else:
        dino_choices = (True, False)

    directory = ROOT / LOCK_DIRECTORY
    directory.mkdir(parents=True, exist_ok=True)
    for variant in variants:
        for include_dino in dino_choices:
            label = f"{variant} ({'pytorch' if include_dino else 'base'})"
            print(f"Resolving {label}...", file=sys.stderr, flush=True)
            entries = _resolve(variant, include_dino)
            target = ROOT / lock_path_for(variant, include_dino=include_dino)
            target.write_text(_render(entries, variant, include_dino), encoding="utf-8")
            print(f"  wrote {target.relative_to(ROOT)} ({len(entries)} distributions)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
